### ISSUE TITLE
Data for Photorealism

### ISSUE THREAD

**Issue by danperazzo** [sanowar-raihan/nerf-meta#2]
Hello, thank you for sharing the code for this wonderfull research! Is it possible to share the data for the Photorealism data used during the experiments?

**Comment by munshisanowarraihan** [comment]
Hi. For photo-tourism, you need an image collection and their camera poses.

* Get image collection of different landmarks from [image-matching-challenge](https://www.cs.ubc.ca/~kmyi/imw2020/data.html)
* Get poses and bounds from [learnit google drive](https://drive.google.com/drive/folders/1SVHKRQXiRb98q4KHVEbj8eoWxjNS2QLW)

**Comment by danperazzo** [comment]
Got it, thank you! :)
