### ISSUE TITLE
Issue about Single image view synthesis for ShapeNet

### ISSUE THREAD

**Issue by LiXinghui-666** [sanowar-raihan/nerf-meta#5]
I would like to ask about your experimental part in Single image view synthesis for ShapeNet, you are using only one image in the meta-learning stage under the setting of SV Meta, which means that only one image is used for the whole training process to generate the class 360 degree reconstruction effect for all instances？

**Comment by munshisanowarraihan** [comment]
For training, the SV meta setting requires a dataset of an object category. But the dataset contains only a single reference view per scene. See section 4.4  of the [learnit paper](https://arxiv.org/abs/2012.02189) for a detailed discussion.
