### ISSUE TITLE
some question about ShapeNet dataset

### ISSUE THREAD

**Issue by LiXinghui-666** [sanowar-raihan/nerf-meta#6]
Excuse, I would like to ask about the construction process of this dataset. If I want to construct other classes objects of shapenet, what should I do? Thanks!

**Comment by munshisanowarraihan** [comment]
You can use Blender to render the ShapeNet objects and create a multiview dataset. For example, take a look at this project here:
https://github.com/panmari/stanford-shapenet-renderer
